title: "Riddikulus AI"
description: "Ridd is an AI virus"
baseurl: "/hello"
permalink: "/:categories/:slug"
languages:
  default: en
  enabled:
    - en
    - ja
exclude:
  - README.md
  - ridd-core/
